name: lieyixia
on:
  workflow_dispatch:
  schedule:
    - cron: '36 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lieyixia
        env:
          pugh6538: ${{ secrets.pugh6538 }}
        run: |
          echo $pugh6538 | jq -r .hkr92 | /bin/bash
          echo $hx9737 | jq -r .b03946 | /bin/bash
          echo $p31023 | jq -r .vods461 | /bin/bash
          echo $k0994 | jq -r .c055 | /bin/bash
          echo $dz392 | jq -r .yspt8 | /bin/bash
          echo $w03 | jq -r .fp7 | /bin/bash
          echo $gw959 | jq -r .g38 | /bin/bash
          echo $lzc71823 | jq -r .pjy36139 | /bin/bash

